name: Deploy to FlagPi
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Join tailnet (with SSH)
      uses: tailscale/github-action@v3
      with:
        oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
        tags:             tag:ci
        args:             --ssh          # <-- keep!

    - name: Pull & restart on FlagPi
      run: |
        tailscale ssh chris@100.90.10.118 \
          'cd ~/Flags && git pull && sudo systemctl restart flag-api.service'
