name: Deploy to FlagPi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
          version: latest

      - name: Verify Tailscale connection
        run: tailscale status

      - name: Deploy to FlagPi
        run: |
          tailscale ssh chris@100.90.10.118 '
            cd /home/chris/Flags &&
            git pull &&
            sudo systemctl restart flag-api.service
          '
