name: Deploy to FlagPi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
          version: latest

      - name: Verify Tailscale connection
        run: tailscale status

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FLAGPI_SSH_KEY }}

      - name: Add flagpi to known_hosts
        run: |
          MACHINE_IP="$(tailscale ip -4 flagpi)"
          mkdir -p ~/.ssh
          ssh-keyscan -H "$MACHINE_IP" >> ~/.ssh/known_hosts

      - name: Deploy to FlagPi
        run: |
          MACHINE_IP="$(tailscale ip -4 flagpi)"
          ssh chris@"$MACHINE_IP" \
            "cd /home/chris/Flags && git pull && sudo systemctl restart flag-api.service"
