name: Deploy to FlagPi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:flagpi
          version: latest

      - name: Debug Tailscale
        run: |
          tailscale status
          tailscale ip -4

      - name: Deploy to FlagPi (Tailscale SSH)
        run: |
          ssh -o StrictHostKeyChecking=no chris@flagpi \
            'cd /home/chris/Flags && git pull && sudo systemctl restart flag-api.service'
